---

dist: trusty
sudo: required

language: python

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y unar p7zip-full

before_script:
  - pip install tox

script: tox

notifications:
  email: false

matrix:
  include:
    - python: "2.7"
      env: TOXENV=flake8
    - python: "2.7"
      env: TOXENV=py27
    - python: "3.6"
      env: TOXENV=py36
  allow_failures:
    - python: "3.6"
      env: TOXENV=py36
